---
title: "Transformation Problem Demo"
author: "Osman Keshawarz"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction

This code replicates the demonstration of the transformation problem and standard/new interpretations in Basu 2022.

```{r}
# Given Quantities

# Technology (input-output) matrix:

A <- matrix(
    c(186/450, 12/450, 9/459,
      54/21, 6/21, 6/21,
      30/60, 3/60, 15/60),
      ncol = 3)


# Labor input vector
l <- c(18/450, 12/21, 30/60)

# Real wage bundle
b <- c(2, 0, 1/6)

# Net output
y <- c(180, 0, 30)

# Check that col(A) = len(l) & len(b)
dim(A)[1] == length(l) & length(b) & length(y)
```
```{r}
#### Gross Output Vector ####

#Create Identity Matrix
n <- ncol(A)
I <- diag(n)

# solve() gives the inverse, and %*% is the operator
# for matrix multiplication.

Q <- solve(I-A) %*% y
Q
```
```{r}
# The Value System
# Vector of Values:
lambda <- t(l)%*%solve(I-A)
lambda
# Value embodied in the net product is equal to 
# the total labor to produce the gross output
(lambda %*% y) 
(l %*% Q)

# Value of real wage bundle (value of labor power)
vrb <- lambda %*% b
vrb

# Rate of exploitation
e <- (1-vrb)/1

# --------- Price System: 1 --------- #
# -- Rate of profit calculations
# Maximum eigenvalue of A
jj_A <- eigen(A)$values
(lambda_mA <- max(jj_A))
# Maximal rate of profit
(R <- (1/lambda_mA)-1)
# Augmented input matrix
(M <- A + b%*%t(l))
# Maximum eigenvalue of M
jj_M <- eigen(M)$values
(lambda_mM <- max(jj_M))
# Uniform rate of profit
(r_e <- (1/lambda_mM)-1)
r_e
```
```{r}
# Relative Price Calculations
M1 <- I - (1/lambda_mM) * M
M1
# Pre-multiply M1 with a price vector
# Choose any two equations
# Solve for relative prices
# Here we solve in terms of p3
A1 <- M1[1:2,1:2]
A1
b1 <- M1[3,1:2]
b1
(p12 <- solve(t(A1),b1))
p12
```



